//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCapasDDD.Infraestructura.Datos.Persistencia.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casa
    {
        public int CasaID { get; set; }
        public int Numero { get; set; }
        public string Calle { get; set; }
        public int NumeroHabitaciones { get; set; }
        public int NumeroBaños { get; set; }
        public int Pisos { get; set; }
        public decimal MetrosCuadrados { get; set; }
    }
}
